name       : nettle
version    : '3.6'
release    : 20
source     :
    - https://ftp.gnu.org/gnu/nettle/nettle-3.6.tar.gz : d24c0d0f2abffbc8f4f34dcf114b0f131ec3774895f3555922fe2f40f3d5e3f1
license    : LGPL-3.0-or-later
component  :
    - security.crypto
    - bin : security.crypto
    - ^libhogweed : security.library
    - ^libhogweed-32bit : emul32
    - ^libnettle : system.base
    - ^libnettle-devel : programming.devel
    - ^libnettle-32bit : emul32
    - ^libnettle-32bit-devel : programming.devel
summary    :
    - Low level cryptographic library
    - bin : Low level cryptographic library (binary tools)
    - ^libnettle-devel : Development files for libnettle
    - ^libnettle-32bit-devel : 32-bit Development files for libnettle
description: |
    The Nettle package contains the low-level cryptographic library that is designed to fit easily in many contexts.
emul32     : yes
patterns   :
    - ^libnettle-32bit-devel :
        - /usr/lib32/lib*.a
        - /usr/lib32/lib*.so
        - /usr/lib32/pkgconfig
    - ^libnettle-32bit :
        - /usr/lib32/libnettle*.so.*
    - ^libnettle-devel :
        - /usr/include
        - /usr/lib64/lib*.a
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - ^libnettle :
        - /usr/lib64/libnettle*.so.*
        - /usr/share/doc
    - bin :
        - /usr/bin
        - /usr/share/info
    - ^libhogweed-32bit : /usr/lib32/libhogweed*.so.*
    - ^libhogweed : /usr/lib64/libhogweed*.so.*
builddeps  :
    - gmp-32bit-devel
rundeps    :
    - ^libnettle-32bit :
        - gmp-32bit
        - libgcc-32bit
        - libnettle
    - ^libnettle-32bit-devel :
        - gmp-32bit-devel
        - libnettle-devel
setup      : |
    %configure --enable-shared
build      : |
    %make
install    : |
    %make_install

    chmod 00755 $installdir/%libdir%/lib*.so.*.*
    install -D -m00644 nettle.html $installdir/usr/share/doc/nettle/nettle.html
check      : |
    %make check
